name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  packaging:
    name: prepare packaging for Veracode scan
    uses: professional-services-m3corp/security-templates/.github/workflows/veracode-package-template.yml@main
    with:
      javascriptTypescript: true