name: Security Scan

on:
  workflow_dispatch:

jobs:
  call-package-template:
    name: prepare packaging for Veracode scan
    uses: professional-services-m3corp/security-templates/.github/workflows/veracode-package-template.yml@main
    with:
      javascriptTypescript: true

  pipeline-scan:
    name: veracode sast pipeline scan
    needs: [ call-package-template ]
    uses: professional-services-m3corp/security-templates/.github/workflows/veracode-pipeline-scan.yml@main
    with:
      veracodeArtifact: ./veracode_artifact_directory/upload.tar.gz
      policyName: "POV"
      failBuild: false
    secrets: inherit